export const posts = [
  {
    id: 1,
    company: "Google",
    jobTitle: "Software Developement Engineer",
    description:
      "Cards include a few options for working with images. Choose from appending “image caps” at either end of a card, overlaying images with card content, or simply embedding the image in a card.",
    type: "Full Time",
    isClosed: false,
    location: {
      city: "New York",
      country: "USA",
    },
    salary: "$100,000",
    date: {
      post: "2020-01-01",
      ppt: "2020-01-01",
      test: "2020-01-01",
      interview: "2020-01-01",
    },
    unit: "per month",
    poster: "Avinal",
    eligibility: {
      branches: ["CSE", "EE", "ECE", "ME", "CE"],
      graduationYear: ["2020"],
      cgpa: "8.56",
    },
  },
  {
    id: 2,
    company: "Company 2",
    jobTitle: "Job Title 2",
    description: "This is post 2",
    type: "Internship",
    isClosed: true,
    location: {
      city: "New York",
      country: "USA",
    },
    salary: "$100,000",
    date: {
      post: "2020-01-01",
      ppt: "2020-01-01",
      test: "2020-01-01",
      interview: "2020-01-01",
    },
    unit: "per year",
    poster: "Sarita",
    eligibility: {
      branches: ["CSE", "EE", "ECE", "ME", "CE"],
      graduationYear: ["2020", "2019", "2018"],
      cgpa: "8.56",
    },
  },
  {
    id: 3,
    company: "Company 3",
    jobTitle: "Job Title 3",
    description: "This is post 3",
    type: "Full Time + Intership",
    isClosed: false,
    location: {
      city: "New York",
      country: "USA",
    },
    salary: "$100,000",
    date: {
      post: "2020-01-01",
      ppt: "2020-01-01",
      test: "2020-01-01",
      interview: "2020-01-01",
    },
    unit: "per month",
    poster: "Shruti",
    eligibility: {
      branches: ["CSE", "EE", "ECE", "ME", "CE"],
      graduationYear: [2020, 2021],
      cgpa: "8.56",
    },
  },
  {
    id: 4,
    company: "Company 4",
    jobTitle: "Job Title 4",
    description: "This is post 4",
    type: "Internship",
    isClosed: true,
    location: {
      city: "New York",
      country: "USA",
    },
    salary: "$100,000",
    date: {
      post: "2020-01-01",
      ppt: "2020-01-01",
      test: "2020-01-01",
      interview: "2020-01-01",
    },
    unit: "per year",
    poster: "Avinal",
    eligibility: {
      branches: ["CSE", "EE", "ECE", "ME", "CE"],
      graduationYear: [2020, 2021],
      cgpa: "8.56",
    },
  },
];
